// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using b3.DeveloperEvaluation.ORM;

#nullable disable

namespace b3.DeveloperEvaluation.WebApi.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20250213232006_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("b3.DeveloperEvaluation.Domain.Entity.CDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("CDI")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DtInicial")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("IR")
                        .HasColumnType("double precision");

                    b.Property<double>("TB")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TituloId")
                        .HasColumnType("uuid");

                    b.Property<double>("VF")
                        .HasColumnType("double precision");

                    b.Property<double>("VI")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TituloId");

                    b.ToTable("CDBs", (string)null);
                });

            modelBuilder.Entity("b3.DeveloperEvaluation.Domain.Entity.Titulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DtFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NomeTitulo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<double>("Rentabilidade")
                        .HasColumnType("numeric(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Titulos", (string)null);
                });

            modelBuilder.Entity("b3.DeveloperEvaluation.Domain.Entity.CDB", b =>
                {
                    b.HasOne("b3.DeveloperEvaluation.Domain.Entity.Titulo", "Titulo")
                        .WithMany("CDBs")
                        .HasForeignKey("TituloId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Titulo");
                });

            modelBuilder.Entity("b3.DeveloperEvaluation.Domain.Entity.Titulo", b =>
                {
                    b.Navigation("CDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
