// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using b3.DeveloperEvaluation.ORM;

#nullable disable

namespace b3.DeveloperEvaluation.WebApi.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("b3.DeveloperEvaluation.Domain.Entity.CDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("CDI")
                        .HasColumnType("double precision");

                    b.Property<double>("TB")
                        .HasColumnType("double precision");

                    b.Property<double>("VF")
                        .HasColumnType("double precision");

                    b.Property<double>("VI")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CDBs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
